### ISSUE TITLE
Three stations have incorrect locations

### ISSUE THREAD

**Issue by arodland** [AF7TI/girotick#3]
Niue (ND61R), should be lon 190.07 (169.93 W), is currently marked as lon 169.93 (169.93 E).

Santa Maria (SMK26), should be lon 306.29, lat -29,73, is currently marked as lon 307.81, lat -29.69 (this is a relatively small one)

Rome (RO041), should be lon 12.5, lat 41.9, is currently marked as lon 185.92, lat 12.5 (this is a big deal, puts it in the Pacific instead of Europe, and has a big effect on the maps).

**Comment by AF7TI** [comment]
Thanks for catching. I see you fixed; can you create a pull request?

**Comment by AF7TI** [comment]
Ignore my earlier commit the dbsetup.sql got mangled from my earlier barbarism. Prefer to pull your version get back on track. Thanks again, Matt.

**Comment by AF7TI** [comment]
Merged in pull request 4 https://github.com/AF7TI/girotick/pull/4
